import Head from "next/head";
import { Grid } from "../components/commons/Grid";
import { ElfoHinto } from "../components/ElfoHinto/ElfoHinto";

export default function Elfo() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Immagini squadrate con la stessa clipping mask</h1>
        <Grid>
          <ElfoHinto imgUrl="/giulio.png" />
          <ElfoHinto imgUrl="/ester.png" />
          <ElfoHinto imgUrl="/matteo.png" />
          <ElfoHinto imgUrl="/irene.png" />
        </Grid>
        <h1 style={{ marginTop: "64px" }}>
          Immagini ritagliate a mano senza clipping mask
        </h1>
        <h3>
          🔥 L&apos;importante é che le proporzioni siano piú o meno 2x3 🔥
        </h3>
        <Grid>
          {/* <ElfoHinto imgUrl="/giulio-clip.png" noClip />
          <ElfoHinto imgUrl="/ester-clip.png" noClip />
          <ElfoHinto imgUrl="/matteo-clip.png" noClip />
          <ElfoHinto imgUrl="/irene-clip.png" noClip /> */}
          <ElfoHinto imgUrl="/irene-fano.png" noClip />
          <ElfoHinto imgUrl="/roberta-antonini.png" noClip />
        </Grid>
      </main>
    </div>
  );
}
