import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { ElfoHinto } from "../components/ElfoHinto/ElfoHinto";
import styles from "../styles/Home.module.css";

export default function Elfo() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Immagini squadrate con la stessa clipping mask</h1>
        <div className={styles.grid}>
          <ElfoHinto imgUrl="/giulio.png" />
          <ElfoHinto imgUrl="/ester.png" />
          <ElfoHinto imgUrl="/matteo.png" />
          <ElfoHinto imgUrl="/irene.png" />
        </div>
        <h1 style={{ marginTop: "64px" }}>
          Immagini ritagliate a mano senza clipping mask
        </h1>
        <h3>🔥 L&apos;importante é che le proporzioni siano piú o meno 2x3 🔥</h3>
        <div className={styles.grid}>
          <ElfoHinto imgUrl="/giulio-clip.png" noClip />
          <ElfoHinto imgUrl="/ester-clip.png" noClip />
          <ElfoHinto imgUrl="/matteo-clip.png" noClip />
          <ElfoHinto imgUrl="/irene-clip.png" noClip />
        </div>
      </main>
    </div>
  );
}
